name: Go SDK CI

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module: ["yt/go", "library/go/core/log", "library/go/x/xreflect", "library/go/blockcodecs"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go build -v -mod=readonly ./...

      - name: Run tests
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod=readonly ./...

      - name: Run tests with race detector
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod=readonly -race ./...

  send-notifications:
    name: Send notifications
    needs:
      - check
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Git ${{github.ref_type}}: *${{github.ref_name}}*.
            Commit:
            ```
            ${{github.event.head_commit.message}}
            ```
